# Generated by Django 4.2.3 on 2023-09-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phno', models.CharField(max_length=15)),
                ('mailid', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=20)),
                ('materials', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='materials_provided',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
